/* Glossary — word → Persian meaning. Used by tap-to-mean. */
window.__GLOSSARY__ = {
  // Get Ready — objects
  this:"این", gives:"می‌دهد", us:"به ما", an:"یک", easier:"راحت‌تر", life:"زندگی",
  when:"وقتی که", there:"آنجا", is:"است", no:"هیچ", light:"نور",
  people:"مردم", use:"استفاده می‌کنند", to:"برای", talk:"صحبت کردن", with:"با",
  someone:"کسی", in:"در", another:"دیگر", place:"مکان", places:"جاها",
  we:"ما", take:"گرفتن", and:"و", keep:"نگه داشتن", pictures:"عکس‌ها",
  very:"خیلی", easily:"به‌راحتی", helps:"کمک می‌کند", travel:"سفر کردن",
  fast:"سریع", far:"دور", airplane:"هواپیما", bulb:"لامپ", telephone:"تلفن",
  camera:"دوربین", building:"ساختمان", laboratory:"آزمایشگاه", scientists:"دانشمندان",
  modern:"مدرن", iranian:"ایرانی", old:"قدیمی", scientist:"دانشمند",
  // Conversation
  library:"کتابخانه", leaving:"در حال ترک کردن", came:"آمد", were:"بودند",
  reading:"در حال خواندن", book:"کتاب", what:"چه", was:"بود", it:"آن",
  about:"درباره", famous:"معروف", but:"اما", such:"چنین", books:"کتاب‌ها",
  are:"هستند", not:"نه", interesting:"جالب", at:"در", first:"اول",
  had:"داشتم", same:"یکسان", idea:"ایده", believe:"باور کن", me:"من",
  did:"آیا", you:"تو", find:"پیدا کردن", useful:"مفید", oh:"آه", yes:"بله",
  actually:"در واقع", learned:"یاد گرفتم", many:"خیلی", things:"چیزها",
  our:"ما", lives:"زندگی‌ها", like:"مثل", for:"برای", example:"مثال",
  razi:"رازی", taught:"درس داد", medicine:"پزشکی", young:"جوان",
  while:"در حالی که", he:"او", working:"در حال کار کردن", ray:"ری",
  hospital:"بیمارستان", or:"یا", nasireddin:"خواجه نصیرالدین", toosi:"طوسی",
  built:"ساخت", maragheh:"مراغه", observatory:"رصدخانه", studying:"در حال مطالعه",
  planets:"سیارات", cool:"عالی", name:"نام", sooner:"زودتر", any:"هیچ",
  story:"داستان", build:"ساختن",
  // Vocabulary
  melika:"ملیکا", tries:"تلاش می‌کند", hard:"سخت", learn:"یاد گرفتن", english:"انگلیسی",
  babak:"بابک", energetic:"پرانرژی", boy:"پسر", students:"دانش‌آموزان",
  do:"انجام دادن", experiments:"آزمایش‌ها", school:"مدرسه",
  children:"کودکان", grow:"رشد می‌کنند", up:"بالا", rapidly:"به‌سرعت",
  she:"او", doing:"در حال انجام دادن", research:"تحقیق", on:"روی",
  blood:"خون", cells:"سلول‌ها", has:"دارد", flu:"آنفولانزا", feels:"احساس می‌کند",
  weak:"ضعیف", success:"موفقیت", possible:"ممکن", without:"بدون", work:"کار",
  edison:"ادیسون", invented:"اختراع کرد", solve:"حل کردن", develop:"توسعه دادن",
  belief:"باور", quit:"رها کردن", give:"دادن", thousands:"هزاران", of:"از",
  answer:"پاسخ", problem:"مسئله", into:"به", stronger:"قوی‌تر", larger:"بزرگ‌تر",
  better:"بهتر", form:"شکل", something:"چیزی", that:"که", stop:"متوقف کردن",
  large:"بزرگ", number:"تعداد", humans:"انسان‌ها", human:"انسانی",
  knowledge:"دانش", develops:"توسعه می‌یابد", facts:"واقعیت‌ها", problems:"مسائل",
  invent:"اختراع کردن", easy:"آسان", have:"داشتن", felt:"احساس کردند",
  never:"هرگز", gave:"دادند", great:"عالی", one:"یک", thomas:"توماس",
  as:"به عنوان", interested:"علاقه‌مند", science:"علم", always:"همیشه",
  asked:"پرسید", questions:"سؤال‌ها", sadly:"متأسفانه", lost:"از دست داد",
  his:"او", hearing:"شنوایی", age:"سن", attend:"حضور یافتن", himself:"خودش",
  grew:"رشد کرد", different:"مختلف", interest:"علاقه", making:"ساختن",
  thousand:"هزار", answers:"پاسخ‌ها", get:"گرفتن", after:"بعد از",
  said:"گفت", until:"تا اینکه", more:"بیشتر", than:"از", inventions:"اختراعات",
  successful:"موفق", end:"پایان", key:"کلید", their:"آن‌ها",
  themselves:"خودشان", want:"خواستن", if:"اگر", pain:"درد", gain:"دستاورد",
  // Grammar examples
  computer:"کامپیوتر", difficult:"سخت", power:"برق", went:"رفت", out:"بیرون",
  tina:"تینا", novel:"رمان", mother:"مادر", rang:"زنگ خورد", reza:"رضا",
  math:"ریاضی", newton:"نیوتون", sitting:"نشستن", under:"زیر", tree:"درخت",
  apple:"سیب", hit:"خورد", head:"سر", mahsa:"مهسا", homework:"تکالیف",
  called:"زنگ زد", teacher:"معلم", noise:"سر و صدا", workers:"کارگران",
  jim:"جیم", car:"ماشین", white:"سفید", broke:"شکست", window:"پنجره",
  why:"چرا", so:"اینقدر", much:"زیاد", yesterday:"دیروز", raining:"باریدن",
  living:"نشیمن", room:"اتاق", watched:"تماشا کرد", movie:"فیلم",
  // Self pronouns
  alexander:"الکساندر", graham:"گراهام", bell:"بِل", marie:"ماری", curie:"کوری",
  found:"پیدا کرد", uranium:"اورانیوم", myself:"خودم", yourself:"خودت",
  herself:"خودش (مؤنث)", itself:"خودش (شیء)", ourselves:"خودمان",
  yourselves:"خودتان", // themselves already defined
  // Writing
  action:"کنشی", state:"حالتی", verbs:"افعال", bus:"اتوبوس", brother:"برادر",
  drinks:"می‌نوشد", milk:"شیر", every:"هر", day:"روز", allah:"خدا",
  love:"دوست داشتن", country:"کشور", happy:"خوشحال", newspapers:"روزنامه‌ها",
  needed:"نیاز داشت", taxi:"تاکسی", moment:"لحظه", television:"تلویزیون",
  cinema:"سینما", tonight:"امشب", unfortunately:"متأسفانه", remember:"به یاد آوردن",
  kids:"بچه‌ها", chocolate:"شکلات", street:"خیابان",
  // Listening
  sajjad:"سجاد", taking:"گرفتن", firefighters:"آتش‌نشانان", jumped:"پریدند",
  quickly:"به‌سرعت", putting:"خاموش کردن", fire:"آتش", standing:"ایستادن",
  near:"نزدیک", watching:"تماشا کردن", dangerous:"خطرناک", put:"گذاشت",
  aside:"کنار", leave:"ترک کردن", yard:"حیاط", kitty:"بچه‌گربه",
  cookie:"بیسکویت", hungry:"گرسنه", hall:"سالن", suddenly:"به‌طور ناگهانی",
  // People
  tahereh:"طاهره", saffarzadeh:"صفارزاده", writer:"نویسنده",
  translator:"مترجم", thinker:"اندیشمند", learned_reading:"خواندن را یاد گرفت",
  reciting:"تلاوت کردن", holy:"مقدس", quran:"قرآن",
  fleming:"فلمینگ", researcher:"پژوهشگر", antibiotics:"آنتی‌بیوتیک‌ها",
  penicillin:"پنی‌سیلین", patient:"بیمار", winter:"زمستان"
};