/* Glossary — word → Persian meaning. Used by tap-to-mean. */
window.__GLOSSARY__ = {
  // Get Ready — objects
  this:"این", gives:"می‌دهد", us:"به ما", an:"یک", easier:"راحت‌تر", life:"زندگی",
  when:"وقتی که", there:"آنجا", is:"است", no:"هیچ", light:"نور",
  people:"مردم", use:"استفاده می‌کنند", to:"برای", talk:"صحبت کردن", with:"با",
  someone:"کسی", in:"در", another:"دیگر", place:"مکان", places:"جاها",
  we:"ما", take:"گرفتن", and:"و", keep:"نگه داشتن", pictures:"عکس‌ها",
  very:"خیلی", easily:"به‌راحتی", helps:"کمک می‌کند", travel:"سفر کردن",
  fast:"سریع", far:"دور", airplane:"هواپیما", bulb:"لامپ", telephone:"تلفن",
  camera:"دوربین", building:"ساختمان", laboratory:"آزمایشگاه", scientists:"دانشمندان",
  modern:"مدرن", iranian:"ایرانی", old:"قدیمی", scientist:"دانشمند",
  // Conversation
  library:"کتابخانه", leaving:"در حال ترک کردن", came:"آمد", were:"بودند",
  reading:"در حال خواندن", book:"کتاب", what:"چه", was:"بود", it:"آن",
  about:"درباره", famous:"معروف", but:"اما", such:"چنین", books:"کتاب‌ها",
  are:"هستند", not:"نه", interesting:"جالب", at:"در", first:"اول",
  had:"داشتم", same:"یکسان", idea:"ایده", believe:"باور کن", me:"من",
  did:"آیا", you:"تو", find:"پیدا کردن", useful:"مفید", oh:"آه", yes:"بله",
  actually:"در واقع", learned:"یاد گرفتم", many:"خیلی", things:"چیزها",
  our:"ما", lives:"زندگی‌ها", like:"مثل", for:"برای", example:"مثال",
  razi:"رازی", taught:"درس داد", medicine:"پزشکی", young:"جوان",
  while:"در حالی که", he:"او", working:"در حال کار کردن", ray:"ری",
  hospital:"بیمارستان", or:"یا", nasireddin:"خواجه نصیرالدین", toosi:"طوسی",
  built:"ساخت", maragheh:"مراغه", observatory:"رصدخانه", studying:"در حال مطالعه",
  planets:"سیارات", cool:"عالی", name:"نام", sooner:"زودتر", any:"هیچ",
  story:"داستان", build:"ساختن",
  // Vocabulary
  melika:"ملیکا", tries:"تلاش می‌کند", hard:"سخت", learn:"یاد گرفتن", english:"انگلیسی",
  babak:"بابک", energetic:"پرانرژی", boy:"پسر", students:"دانش‌آموزان",
  do:"انجام دادن", experiments:"آزمایش‌ها", school:"مدرسه",
  children:"کودکان", grow:"رشد می‌کنند", up:"بالا", rapidly:"به‌سرعت",
  she:"او", doing:"در حال انجام دادن", research:"تحقیق", on:"روی",
  blood:"خون", cells:"سلول‌ها", has:"دارد", flu:"آنفولانزا", feels:"احساس می‌کند",
  weak:"ضعیف", success:"موفقیت", possible:"ممکن", without:"بدون", work:"کار",
  edison:"ادیسون", invented:"اختراع کرد", solve:"حل کردن", develop:"توسعه دادن",
  belief:"باور", quit:"رها کردن", give:"دادن", thousands:"هزاران", of:"از",
  answer:"پاسخ", problem:"مسئله", into:"به", stronger:"قوی‌تر", larger:"بزرگ‌تر",
  better:"بهتر", form:"شکل", something:"چیزی", that:"که", stop:"متوقف کردن",
  large:"بزرگ", number:"تعداد", humans:"انسان‌ها", human:"انسانی",
  knowledge:"دانش", develops:"توسعه می‌یابد", facts:"واقعیت‌ها", problems:"مسائل",
  invent:"اختراع کردن", easy:"آسان", have:"داشتن", felt:"احساس کردند",
  never:"هرگز", gave:"دادند", great:"عالی", one:"یک", thomas:"توماس",
  as:"به عنوان", interested:"علاقه‌مند", science:"علم", always:"همیشه",
  asked:"پرسید", questions:"سؤال‌ها", sadly:"متأسفانه", lost:"از دست داد",
  his:"او", hearing:"شنوایی", age:"سن", attend:"حضور یافتن", himself:"خودش",
  grew:"رشد کرد", different:"مختلف", interest:"علاقه", making:"ساختن",
  thousand:"هزار", answers:"پاسخ‌ها", get:"گرفتن", after:"بعد از",
  said:"گفت", until:"تا اینکه", more:"بیشتر", than:"از", inventions:"اختراعات",
  successful:"موفق", end:"پایان", key:"کلید", their:"آن‌ها",
  themselves:"خودشان", want:"خواستن", if:"اگر", pain:"درد", gain:"دستاورد",
  // Grammar examples
  computer:"کامپیوتر", difficult:"سخت", power:"برق", went:"رفت", out:"بیرون",
  tina:"تینا", novel:"رمان", mother:"مادر", rang:"زنگ خورد", reza:"رضا",
  math:"ریاضی", newton:"نیوتون", sitting:"نشستن", under:"زیر", tree:"درخت",
  apple:"سیب", hit:"خورد", head:"سر", mahsa:"مهسا", homework:"تکالیف",
  called:"زنگ زد", teacher:"معلم", noise:"سر و صدا", workers:"کارگران",
  jim:"جیم", car:"ماشین", white:"سفید", broke:"شکاند", window:"پنجره",
  why:"چرا", so:"اینقدر", much:"زیاد", yesterday:"دیروز", raining:"باریدن",
  living:"نشیمن", room:"اتاق", watched:"تماشا کرد", movie:"فیلم",
  // Self pronouns
  alexander:"الکساندر", graham:"گراهام", bell:"بِل", marie:"ماری", curie:"کوری",
  found:"پیدا کرد", uranium:"اورانیوم", myself:"خودم", yourself:"خودت",
  herself:"خودش (مؤنث)", itself:"خودش (شیء)", ourselves:"خودمان",
  yourselves:"خودتان", // themselves already defined
  // Writing
  action:"کنشی", state:"حالتی", verbs:"افعال", bus:"اتوبوس", brother:"برادر",
  drinks:"می‌نوشد", milk:"شیر", every:"هر", day:"روز", allah:"خدا",
  love:"دوست داشتن", country:"کشور", happy:"خوشحال", newspapers:"روزنامه‌ها",
  needed:"نیاز داشت", taxi:"تاکسی", moment:"لحظه", television:"تلویزیون",
  cinema:"سینما", tonight:"امشب", unfortunately:"متأسفانه", remember:"به یاد آوردن",
  kids:"بچه‌ها", chocolate:"شکلات", street:"خیابان",
  // Listening
  sajjad:"سجاد", taking:"گرفتن", firefighters:"آتش‌نشانان", jumped:"پریدند",
  quickly:"به‌سرعت", putting:"خاموش کردن", fire:"آتش", standing:"ایستادن",
  near:"نزدیک", watching:"تماشا کردن", dangerous:"خطرناک", put:"گذاشت",
  aside:"کنار", leave:"ترک کردن", yard:"حیاط", kitty:"بچه‌گربه",
  cookie:"بیسکویت", hungry:"گرسنه", hall:"سالن", suddenly:"به‌طور ناگهانی",
  // People
  tahereh:"طاهره", saffarzadeh:"صفارزاده", writer:"نویسنده",
  translator:"مترجم", thinker:"اندیشمند", translate:"ترجمه کردن",
  reciting:"تلاوت کردن", holy:"مقدس", quran:"قرآن",
  fleming:"فلمینگ", researcher:"پژوهشگر", antibiotics:"آنتی‌بیوتیک‌ها",
  penicillin:"پنی‌سیلین", patient:"بیمار", winter:"زمستان",
  // Lesson 1 — supplementary readings & extra content
  outside:"بیرون", playing:"در حال بازی کردن", student:"دانشجو",
  writing:"نوشتن", poems:"شعرها", poem:"شعر", published:"منتشر کرد",
  university:"دانشگاه", translation:"ترجمه", translating:"ترجمه کردن",
  teaching:"تدریس کردن", passed:"گذشت", away:"دور", save:"نجات دادن",
  amazing:"شگفت‌انگیز", doctors:"پزشکان", doctor:"پزشک",
  getting:"شدن", around:"این‌طرف و آن‌طرف", those:"آن‌ها", days:"روزها",
  also:"همچنین", help:"کمک کردن", inventor:"مخترع",
  kashani:"کاشانی", ghiyath:"غیاث", jamshid:"جمشید", "al-din":"الدین", kashan:"کاشان",
  numbers:"اعداد", solving:"حل کردن", solved:"حل کرد", short:"کوتاه",
  killing:"کشتن", killed:"کشت", worked:"کار کرد", forty:"چهل", two:"دو",
  mina:"مینا", dress:"لباس", leila:"لیلا", driver:"راننده",
  cleaned:"تمیز کرد", know:"دانستن", read:"خواندن", wrote:"نوشت",
  takes:"می‌گیرد", took:"گرفت", understand:"فهمیدن", talking:"صحبت کردن",
  long:"طولانی", hours:"ساعت‌ها", hour:"ساعت", tried:"تلاش کرد",
  trying:"در حال تلاش", kitchen:"آشپزخانه", poor:"بیچاره",
  firefighter:"آتش‌نشان", pushed:"هل داد", loudly:"با صدای بلند",
  // Function words & pronouns
  the:"حرف تعریف (the)", i:"من", a:"یک", they:"آن‌ها", my:"مالِ من",
  her:"او / مالِ او", him:"او (مفعولی)", them:"آن‌ها (مفعولی)", its:"مالِ آن",
  these:"این‌ها", from:"از", who:"چه کسی", can:"توانستن", your:"مالِ تو",
  which:"کدام", other:"دیگر", all:"همه", be:"بودن", how:"چگونه",
  where:"کجا", some:"بعضی", will:"خواستن / خواهد", by:"توسط",
  "scientist's":"مالِ دانشمند", "scientists'":"مالِ دانشمندان", "razi's":"مالِ رازی",
  // Auxiliaries & common verbs
  am:"هستم", "wasn't":"نبود", "weren't":"نبودند", "didn't":"نکرد", "don't":"نکن",
  "i'm":"من هستم", does:"انجام می‌دهد", mean:"یعنی", means:"یعنی",
  used:"استفاده شد", shows:"نشان می‌دهد", wanted:"می‌خواست", try:"تلاش کردن",
  lose:"از دست دادن", hear:"شنیدن", heard:"شنید", see:"دیدن", saw:"دید",
  look:"نگاه کردن", made:"ساخت", sleep:"خوابیدن", slept:"خوابید",
  sleeping:"در حال خواب", play:"بازی کردن", played:"بازی کرد", plays:"بازی می‌کند",
  study:"درس خواندن", finish:"تمام کردن", finished:"تمام کرد", write:"نوشتن",
  runs:"می‌دود", go:"رفتن", going:"در حال رفتن", come:"آمدن",
  eat:"خوردن", eating:"در حال خوردن", drink:"نوشیدن", drinking:"در حال نوشیدن",
  buy:"خریدن", destroy:"نابود کردن", repair:"تعمیر کردن", decided:"تصمیم گرفت",
  need:"نیاز داشتن", remembered:"به یاد آورد", knew:"می‌دانست", liked:"دوست داشت",
  loved:"دوست داشت", watches:"تماشا می‌کند", watch:"تماشا کردن",
  walking:"در حال قدم زدن", painted:"رنگ کرد", hurt:"آسیب زدن", waking:"بیدار شدن",
  // People, places & things
  roya:"رویا", tv:"تلویزیون", football:"فوتبال", father:"پدر", sister:"خواهر",
  night:"شب", morning:"صبح", afternoon:"بعدازظهر", weekend:"آخر هفته",
  tomorrow:"فردا", park:"پارک", house:"خانه", home:"خانه", sun:"خورشید",
  sky:"آسمان", star:"ستاره", stars:"ستاره‌ها", stories:"داستان‌ها",
  experiment:"آزمایش", cake:"کیک", cat:"گربه", sofa:"مبل", party:"مهمانی",
  thief:"دزد", cars:"ماشین‌ها", money:"پول", luck:"شانس", fame:"شهرت",
  man:"مرد", men:"مردان", woman:"زن", women:"زنان", names:"نام‌ها",
  smoking:"سیگار کشیدن", glass:"شیشه", trip:"سفر", lesson:"درس",
  mathematics:"ریاضیات", astronomy:"نجوم", history:"تاریخ", skill:"مهارت",
  hope:"امید", reason:"دلیل", thing:"چیز", world:"جهان",
  // Lesson / exercise vocabulary
  word:"کلمه", words:"کلمه‌ها", sentence:"جمله", verb:"فعل",
  past:"گذشته", progressive:"استمراری", adjectives:"صفت‌ها", nouns:"اسم‌ها",
  progress:"پیشرفت", structure:"ساختار", background:"پس‌زمینه", part:"بخش",
  longer:"طولانی‌تر", true:"درست", false:"غلط", correct:"درست",
  right:"درست / راست", wrong:"اشتباه", last:"آخرین",
  according:"طبق", paragraph:"پاراگراف", emphasized:"تأکید شد",
  recently:"به‌تازگی", finally:"سرانجام", inventing:"در حال اختراع",
  giving:"در حال دادن", quitting:"در حال رها کردن", before:"قبل از",
  between:"بین", forward:"به جلو", moves:"حرکت می‌دهد", continued:"ادامه یافت",
  shines:"می‌درخشد", woke:"بیدار شد", theirselves:"خودشان (غلط)",
  themself:"خودش (غلط)", "self-belief":"باور به خود", "verb-ing":"فعل + ing",
  "o'clock":"ساعت", pm:"بعدازظهر",
  phone:"تلفن", project:"پروژه", iran:"ایران", conversation:"مکالمه",
  medical:"پزشکی", teach:"درس دادن", speaking:"صحبت کردن", strong:"قوی",
  now:"اکنون", baby:"نوزاد", sleeps:"می‌خوابد", loving:"دوست داشتن",
  friday:"جمعه", slowly:"به‌آرامی", reads:"می‌خواند", feel:"احساس کردن",
  noises:"سر و صداها",
  ali:"علی", wanting:"خواستن", remembering:"به یاد آوردن", shining:"درخشیدن",
  liking:"دوست داشتن", needing:"نیاز داشتن", knowing:"دانستن",
  new:"جدید", still:"هنوز", simple:"ساده", time:"زمان", got:"گرفت",
  helped:"کمک کرد", job:"شغل", planet:"سیاره", tells:"می‌گوید",
  present:"حال", during:"در طول، طی", only:"فقط", year:"سال", years:"سال‌ها",
  studied:"درس خواند", over:"بالای / بیش از", cleaning:"تمیز کردن",
  "mina's":"مالِ مینا", "jim's":"مالِ جیم", "saffarzadeh's":"مالِ صفارزاده",
  "people's":"مالِ مردم", "-ing":"پسوند ing",
  rained:"بارید", rains:"می‌بارد", sit:"نشستن", solves:"حل می‌کند",
  having:"داشتن", kills:"می‌کشد", works:"کار می‌کند", finishes:"تمام می‌کند"
};